project:
  type: website
  render:
    - index.qmd
    - "tutorials/"
    - "*.md"
    - about.qmd
    - "!contributing/*"
    - "!notebooks/*"

website:
  title: "HySchool"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorials/tutorials.md
        text: Tutorials
      - about.qmd

  search:
    location: navbar 
    type: overlay
  sidebar:
    style: "floating"
    contents:
      - section: "Basics"
        contents:
        - index.qmd
        - about.qmd
      - section: "Tutorials"
        contents:
          - tutorials/tutorials.md
          - tutorials/think-bayes.qmd
          - tutorials/chap01_ex.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



